# my global config
global:
  scrape_interval: 5s  # Ambil data setiap 5 detik

# Scrape configuration
scrape_configs:
  - job_name: 'ml_model_exporter'
    static_configs:
      - targets: ['127.0.0.1:8000']

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# prometheus --config.file=prometheus.yml