name: Build & Push Model Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      mlflow_run_id:
        description: 'MLflow Run ID of the model to deploy (e.g., from training workflow logs)'
        required: false
        type: string

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      MLFLOW_ARTIFACTS_REPO_PATH: "mlflow-artifacts" 

    steps:
      - name: Checkout Workflow Repository
        uses: actions/checkout@v3

      - name: Clone MLflow Artifacts Repository
        run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://x-access-token:${{ secrets.ARTIFACT_TOKEN }}@github.com/MohPras/mlflow-artifacts.git ${{ env.MLFLOW_ARTIFACTS_REPO_PATH }}
        env:
          ARTIFACT_TOKEN: ${{ secrets.ARTIFACT_TOKEN }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install MLflow
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Set MLflow Tracking URI to Cloned Repo
        run: |
          echo "MLFLOW_TRACKING_URI=${{ github.workspace }}/${{ env.MLFLOW_ARTIFACTS_REPO_PATH }}" >> $GITHUB_ENV
          echo "DEBUG: MLFLOW_TRACKING_URI set to: ${{ github.workspace }}/${{ env.MLFLOW_ARTIFACTS_REPO_PATH }}"

      - name: Determine MLflow Run ID
        id: get_selected_run_id
        run: |
          RUN_ID=""
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.mlflow_run_id }}" ]]; then
            RUN_ID="${{ github.event.inputs.mlflow_run_id }}"
            echo "DEBUG: Using Run ID from manual input: $RUN_ID"
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "DEBUG: Finding the latest MLflow Run ID from the cloned artifacts repository..."
            LATEST_RUN_ID=$(find ${{ env.MLFLOW_ARTIFACTS_REPO_PATH }}/0 -maxdepth 1 -type d -regextype egrep -regex '.*/[0-9a-f]{32}' | sort | tail -n 1)
            
            if [ -z "$LATEST_RUN_ID" ]; then
              echo "ERROR: Could not find a valid MLflow Run ID in the artifacts repository for automated push deployment."
              exit 1
            fi
            RUN_ID=$(basename "$LATEST_RUN_ID")
            echo "DEBUG: Latest MLflow Run ID found for push trigger: $RUN_ID"
          else
            echo "ERROR: No valid MLflow Run ID provided or could not be determined for this trigger type."
            exit 1
          fi
          echo "SELECTED_RUN_ID=$RUN_ID" >> $GITHUB_ENV # Set for subsequent steps

      # --- PERBAIKAN UTAMA DI SINI ---
      - name: Download MLflow Model Locally
        run: |
          MODEL_SOURCE_URI="runs:/${{ env.SELECTED_RUN_ID }}/artifacts/model"
          LOCAL_MODEL_PATH="./downloaded_mlflow_model" # Direktori lokal untuk menyimpan model
          
          echo "DEBUG: Downloading model from '$MODEL_SOURCE_URI' to '$LOCAL_MODEL_PATH'"
          mlflow artifacts download --artifact-uri "$MODEL_SOURCE_URI" --dst-path "$LOCAL_MODEL_PATH"
          
          # Debugging: List isi direktori yang diunduh
          echo "DEBUG: Contents of downloaded model directory:"
          ls -lR "$LOCAL_MODEL_PATH"
          
          # Cek apakah file MLmodel ada di sana
          if [ -f "$LOCAL_MODEL_PATH/MLmodel" ]; then
            echo "SUCCESS: 'MLmodel' file found in downloaded path."
          else
            echo "CRITICAL ERROR: 'MLmodel' file NOT found in downloaded path. Download failed or model structure is incorrect."
            exit 1
          fi

      - name: Build Docker Image
        # Sekarang, model_uri menunjuk ke path lokal yang sudah diunduh
        run: |
          echo "DEBUG: Attempting to build Docker image from LOCAL model path: ./downloaded_mlflow_model"
          mlflow models build-docker --model-uri "./downloaded_mlflow_model" --name "iot-model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag iot-model ${{ secrets.DOCKER_HUB_USERNAME }}/iot-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/iot-model:latest
