name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=file:/tmp/mlruns" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: |
          mlflow run Workflow-CI/MLproject --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td /tmp/mlruns/0/*/ | head -n 1 | cut -d'/' -f5)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Image
        run: |
          mlflow models build-docker --model-uri "file:/tmp/mlruns/0/$RUN_ID/artifacts/model" --name "iot-model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag iot-model ${{ secrets.DOCKER_HUB_USERNAME }}/iot-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/iot-model:latest