name: CI Training & Evaluasi

on:
  push:
    paths:
      - 'Workflow-CI/MLproject/**'
      - '.github/workflows/trainingEvaluasi.yml'
  workflow_dispatch:

env:
  CSV_URL: "Workflow-CI/MLproject/netflix_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ... (Langkah-langkah Checkout Repository, Set up Python, Install dependencies) ...

      - name: Set MLflow tracking URI
        run: echo "MLFLOW_TRACKING_URI=file:/tmp/mlruns" >> $GITHUB_ENV

      - name: Run MLflow Project
        id: run_mlflow # Tambahkan ID ke langkah ini
        run: |
          mlflow run Workflow-CI/MLproject --env-manager=local
        working-directory: Workflow-CI/MLproject

      # --- DEBUGGING BARU DI TRAINING WORKFLOW ---
      - name: Verify MLflow Run Artifacts Locally
        run: |
          echo "--- DEBUGGING ARTIFACTS IN /tmp/mlruns AFTER TRAINING ---"
          # Ambil RUN_ID dari output langkah sebelumnya
          RUN_ID=$(cat ${{ github.workspace }}/Workflow-CI/MLproject/.mlflow/mlruns/0/latest_run_id.txt) # Asumsi: kalau MLflow projectnya berhasil, ini ada.
          
          # Alternatif yang lebih robust (seperti di workflow Docker):
          RUN_ID=$(find /tmp/mlruns/0 -maxdepth 1 -type d -regextype egrep -regex '.*/[0-9a-f]{32}' | sort | tail -n 1)
          if [ -z "$RUN_ID" ]; then
            echo "ERROR: Could not find RUN_ID for artifact verification in /tmp/mlruns."
            exit 1
          fi
          
          echo "Discovered RUN_ID for local verification: $RUN_ID"
          EXPECTED_ARTIFACTS_DIR="/tmp/mlruns/0/$RUN_ID/artifacts"
          echo "Expected local artifacts directory: $EXPECTED_ARTIFACTS_DIR"

          if [ -d "$EXPECTED_ARTIFACTS_DIR" ]; then
            echo "SUCCESS: Local Artifacts directory FOUND. Listing its contents (recursive):"
            ls -lR "$EXPECTED_ARTIFACTS_DIR" # List secara rekursif
            
            if [ -d "$EXPECTED_ARTIFACTS_DIR/model" ]; then
              echo "SUCCESS: 'model' directory FOUND locally within artifacts. Listing its contents:"
              ls -l "$EXPECTED_ARTIFACTS_DIR/model"
              if [ "$(ls -A "$EXPECTED_ARTIFACTS_DIR/model")" ]; then
                echo "INFO: 'model' directory is NOT empty locally. Contains files."
              else
                echo "WARNING: 'model' directory is EMPTY locally. Model logging might have failed internally."
              fi
            elif [ -f "$EXPECTED_ARTIFACTS_DIR/model" ]; then
              echo "SUCCESS: 'model' file FOUND directly locally within artifacts."
            else
              echo "CRITICAL ERROR: 'model' directory or file NOT found LOCALLY within $EXPECTED_ARTIFACTS_DIR. Model was likely not logged despite run success."
              exit 1 # Gagal jika model tidak ditemukan secara lokal
            fi
          else
            echo "CRITICAL ERROR: Local Artifacts directory $EXPECTED_ARTIFACTS_DIR NOT found at all."
            exit 1 # Gagal jika direktori artifacts tidak ada
          fi
          echo "--- END DEBUGGING ARTIFACTS IN /tmp/mlruns ---"
      # --- AKHIR DEBUGGING BARU DI TRAINING WORKFLOW ---

      - name: Upload MLflow Logs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-training-logs
          path: /tmp/mlruns/

      - name: Push MLflow logs to mlflow-artifacts repository
        run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "github-actions[bot]"

          git clone https://x-access-token:${{ secrets.ARTIFACT_TOKEN }}@github.com/MohPras/mlflow-artifacts.git
          # Pastikan path ini menunjuk ke direktori utama di repo mlflow-artifacts
          # Jangan sampai membuat subdirektori berlebihan
          cp -r /tmp/mlruns/* mlflow-artifacts/0/ # Hanya salin isi direktori 0
          
          cd mlflow-artifacts
          git add .
          git commit -m "MLflow logs from CI $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
