name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=file:/tmp/mlruns" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: |
          # Perbaikan di sini: Menggunakan --param-list sesuai saran error
          mlflow run Workflow-CI/MLproject -e main --env-manager=local --param-list csv_url=netflix_preprocessing.csv

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          # Menambahkan debugging untuk melihat direktori yang ditemukan
          echo "Searching for MLflow run directories in /tmp/mlruns/0..."
          find /tmp/mlruns/0 -type d -name "*-*" -print
          
          RUN_DIR=$(find /tmp/mlruns/0 -type d -name "*-*" | sort | tail -n 1)
          RUN_ID=$(basename "$RUN_DIR")
          
          # Menambahkan echo untuk memastikan RUN_ID tertangkap
          echo "Discovered RUN_DIR: $RUN_DIR"
          echo "Discovered RUN_ID: $RUN_ID"
          
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          mlflow models build-docker --model-uri "file:/tmp/mlruns/0/$RUN_ID/artifacts/model" --name "iot-model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag iot-model ${{ secrets.DOCKER_HUB_USERNAME }}/iot-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/iot-model:latest
