name: CI Training & Evaluasi

on:
  push:
    paths:
      - 'Workflow-CI/MLproject/**'
      - '.github/workflows/trainingEvaluasi.yml'
  workflow_dispatch:

env:
  CSV_URL: "Workflow-CI/MLproject/netflix_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Set MLflow tracking URI
        run: echo "MLFLOW_TRACKING_URI=file:/tmp/mlruns" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: |
          mlflow run Workflow-CI/MLproject --env-manager=local

      - name: Upload MLflow Logs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-training-logs
          path: /tmp/mlruns/

      - name: Push MLflow logs to mlflow-artifacts repository
        run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "github-actions[bot]"

          git clone https://x-access-token:${{ secrets.ARTIFACT_TOKEN }}@github.com/MohPras/mlflow-artifacts.git
          cp -r /tmp/mlruns/* mlflow-artifacts/

          cd mlflow-artifacts
          git add .
          git commit -m "MLflow logs from CI $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
