name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "Workflow-CI/MLproject/netflix_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: echo $CSV_URL

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Set MLflow tracking URI
        run: echo "MLFLOW_TRACKING_URI=file:outputs/mlruns" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: |
          mlflow run Workflow-CI/MLproject --env-manager=local

      - name: Commit and Push outputs folder
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add outputs/
          git commit -m "Update MLflow outputs artifacts [CI]" || echo "No changes to commit"
          git push origin main